name: Deploy Jupyter Book

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install jupyter-book ghp-import
    - name: Build Jupyter Book
      run: jupyter-book build .
    - name: Deploy to GitHub Pages
      run: ghp-import -n -p -f _build/html